# This is a basic workflow to help you get started with Actions

name: Auto Get Competition Questions

# Controls when the workflow will run
on:
  issue:
    types: [opened ]
  issue_comment:
    types: [created ]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Pull the newleast Code
      - uses: actions/checkout@v2
      - name: setup chromedriver
        uses: nanasess/setup-chromedriver@v1.0.1
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      - name: Install Dependences
        run: pip install selenium requests demjson
      - name: Trigger WorkFlow
        run: python triggerWorkFlow.py ${{ github.event.issue.number }} ${{ secrets.GITHUB_TOKEN }}
